#! /bin/zsh
#
# vi-mode colour changing
#   http://www.zsh.org/mla/users/2006/msg01196.html

source $HOME/gitrepos/zsh_config/git-status/git_status_prompt.sh

rst="%{%b%s%u$reset_color%}"
bgc="%{%(?.$rst.%S)%}"


function lprompt {
    local col1 col2 ch1 ch2

    col1="%{%b$fg[$2]%}"
    col2="%{$4$fg[$3]%}"

    ch1=$col1${1[1]}
    ch2=$col1${1[2]}


    local col_b col_s

    col_b="%{$fg[green]%}"
    col_s="%{$fg[red]%}"

    PROMPT="$bgc$ch1%{$fg_bold[white]%}%m:$bgc$col2%B%1~%b$ch2$rst $col2%#$rst "
}

function rprompt {
    local col1 col2 ch1 ch2
    col1="%{$fg[$2]%}"
    col2="%{$4$fg[$3]%}"
    ch1=$col1${1[1]}
    ch2=$col1${1[2]}

    local _dvcs='$(git_super_status)'

    RPROMPT="$rst$ch1$col2%*:%n${col1}$col2%B${_dvcs}%b$ch2$rst"
}

if [ $UID -eq 0 ]; then
    PROMPT="$bgc%{%B$fg[yellow]%}[%{$fg[red]%}%n %m%{$fg[yellow]%}]$rst "
    RPROMPT="$rst%{$fg[red]%}(%B%{$fg[red]%}%~%b%{$fg[red]%})$rst "
elif [ -f ~/.zsh.prompt ]; then
    source ~/.zsh.prompt
else
    case $HOST in
        *)
            lprompt '{}' green green
            rprompt '()' yellow white
            ;;
    esac
fi

unset rst bgc
